name: scsc_init_bot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.12.11
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aio-pika==9.5.5
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiormq==6.8.1
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - certifi==2025.6.15
      - click==8.2.1
      - discord-py==2.5.2
      - exceptiongroup==1.3.0
      - fastapi==0.115.14
      - frozenlist==1.7.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - multidict==6.6.3
      - pamqp==3.3.0
      - propcache==0.3.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - python-dotenv==1.1.1
      - redis==6.2.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - yarl==1.20.1
